-- V2: Full baseline schema.
-- -----------------------------------------------------------------------------
-- Single source of truth for the physical schema. The application runs with
-- spring.jpa.hibernate.ddl-auto=validate, and V1 contains no CREATE TABLE
-- statements, so a brand-new database used to have no tables and the app
-- could not boot. This migration creates the complete schema.
--
-- Idempotent for BOTH fresh and existing (legacy Hibernate-created) databases:
--   * CREATE TABLE IF NOT EXISTS  - legacy tables are skipped as-is
--   * FK constraints are name-guarded (PostgreSQL has no ADD CONSTRAINT IF NOT
--     EXISTS, so each FK is added inside a pg_constraint existence check)
--   * unique indexes use CREATE UNIQUE INDEX IF NOT EXISTS
-- -----------------------------------------------------------------------------

-- =============================================================================
-- 1. Tables
-- =============================================================================

CREATE TABLE IF NOT EXISTS academic_terms (
    end_date date not null,
    exam_period_end date,
    exam_period_start date,
    start_date date not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    version bigint not null,
    academic_year varchar(255),
    description TEXT,
    name varchar(255) not null,
    status varchar(255) not null check (status in ('UPCOMING','ACTIVE','CLOSED','ARCHIVED')),
    primary key (id)
);

CREATE TABLE IF NOT EXISTS batch_working_days (
    batch_id bigint not null,
    day varchar(255) check (day in ('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY'))
);

CREATE TABLE IF NOT EXISTS batches (
    student_count integer not null check (student_count>=1),
    year integer not null check (year>=1),
    created_at timestamp(6) not null,
    department_id bigint not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    version bigint not null,
    section varchar(10) not null,
    preferred_free_day varchar(255) check (preferred_free_day in ('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY')),
    primary key (id),
    unique (department_id, year, section)
);

CREATE TABLE IF NOT EXISTS buildings (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    version bigint not null,
    location varchar(255),
    name varchar(255) not null,
    primary key (id),
    unique (name)
);

CREATE TABLE IF NOT EXISTS class_sections (
    size integer not null check (size>=1),
    batch_id bigint not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    version bigint not null,
    label varchar(10) not null,
    primary key (id),
    unique (batch_id, label)
);

CREATE TABLE IF NOT EXISTS class_sessions (
    duration integer not null check (duration>=1),
    is_locked boolean not null,
    batch_id bigint,
    id bigint generated by default as identity,
    room_id bigint,
    schedule_id bigint not null,
    section_id bigint,
    subject_id bigint not null,
    teacher_id bigint,
    timeslot_id bigint,
    primary key (id)
);

CREATE TABLE IF NOT EXISTS config_break_indices (
    slot_index integer,
    config_id bigint not null
);

CREATE TABLE IF NOT EXISTS config_working_days (
    config_id bigint not null,
    day varchar(255) check (day in ('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY'))
);

CREATE TABLE IF NOT EXISTS department_buildings (
    building_id bigint not null,
    department_id bigint not null
);

CREATE TABLE IF NOT EXISTS departments (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    version bigint not null,
    code varchar(20) not null unique,
    name varchar(120) not null unique,
    primary key (id)
);

CREATE TABLE IF NOT EXISTS event_affected_rooms (
    event_id bigint not null,
    room_id bigint not null
);

CREATE TABLE IF NOT EXISTS event_affected_teachers (
    event_id bigint not null,
    teacher_id bigint not null
);

CREATE TABLE IF NOT EXISTS event_affected_timeslots (
    event_id bigint not null,
    timeslot_id bigint not null
);

CREATE TABLE IF NOT EXISTS events (
    end_date date,
    start_date date,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    version bigint not null,
    description TEXT,
    title varchar(255) not null,
    type varchar(255) not null check (type in ('EXAM','FESTIVAL','MAINTENANCE','TEACHER_LEAVE','GUEST_LECTURE','SPORTS_DAY','SEMINAR','HOLIDAY','OTHER')),
    primary key (id)
);

CREATE TABLE IF NOT EXISTS pre_allocations (
    locked boolean not null,
    batch_id bigint not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    room_id bigint,
    schedule_id bigint not null,
    subject_id bigint not null,
    teacher_id bigint,
    timeslot_id bigint not null,
    updated_at timestamp(6) not null,
    version bigint not null,
    primary key (id)
);

CREATE TABLE IF NOT EXISTS room_availability (
    room_id bigint not null,
    timeslot_id bigint not null
);

CREATE TABLE IF NOT EXISTS rooms (
    capacity integer not null check (capacity>=1),
    building_id bigint not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    version bigint not null,
    room_number varchar(30) not null,
    lab_subtype varchar(255) check (lab_subtype in ('COMPUTER_LAB','ELECTRONICS_LAB','CHEMISTRY_LAB','PHYSICS_LAB','MECHANICAL_LAB','CIVIL_LAB','NETWORK_LAB','GENERAL_LAB')),
    type varchar(255) not null check (type in ('LECTURE','LAB')),
    primary key (id),
    unique (building_id, room_number)
);

CREATE TABLE IF NOT EXISTS schedules (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    parent_schedule_id bigint,
    updated_at timestamp(6) not null,
    version bigint not null,
    name varchar(255) not null,
    scope varchar(255) not null check (scope in ('DEPARTMENT','COLLEGE','UNIVERSITY')),
    score varchar(255),
    score_explanation TEXT,
    status varchar(255) not null check (status in ('DRAFT','ACTIVE','ARCHIVED','PARTIAL','INFEASIBLE')),
    primary key (id)
);

CREATE TABLE IF NOT EXISTS subjects (
    chunk_hours integer not null check (chunk_hours>=1),
    is_lab boolean not null,
    max_sessions_per_day integer not null check (max_sessions_per_day>=1),
    min_gap_between_sessions integer not null check (min_gap_between_sessions>=0),
    requires_room boolean not null,
    requires_teacher boolean not null,
    weekly_hours integer not null check (weekly_hours>=1),
    created_at timestamp(6) not null,
    department_id bigint not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    version bigint not null,
    code varchar(30),
    lab_subtype_required varchar(255) check (lab_subtype_required in ('COMPUTER_LAB','ELECTRONICS_LAB','CHEMISTRY_LAB','PHYSICS_LAB','MECHANICAL_LAB','CIVIL_LAB','NETWORK_LAB','GENERAL_LAB')),
    name varchar(255) not null,
    room_type_required varchar(255) not null check (room_type_required in ('LECTURE','LAB')),
    primary key (id)
);

CREATE TABLE IF NOT EXISTS teacher_availability (
    teacher_id bigint not null,
    timeslot_id bigint not null
);

CREATE TABLE IF NOT EXISTS teacher_preferred_buildings (
    building_id bigint not null,
    teacher_id bigint not null
);

CREATE TABLE IF NOT EXISTS teacher_subjects (
    subject_id bigint not null,
    teacher_id bigint not null
);

CREATE TABLE IF NOT EXISTS teachers (
    max_consecutive_classes integer not null check (max_consecutive_classes>=1),
    max_daily_hours integer not null check (max_daily_hours>=1),
    max_weekly_hours integer not null check (max_weekly_hours>=1),
    movement_penalty integer not null check (movement_penalty>=0),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    version bigint not null,
    name varchar(120) not null,
    preferred_free_day varchar(255) check (preferred_free_day in ('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY')),
    primary key (id)
);

-- NOTE: timeslots intentionally does NOT declare a unique constraint on
-- (day, slot_number). Multi-slot ordering must allow rows with NULL
-- slot_number; uniqueness for populated slot numbers is enforced by the
-- partial unique index uk_timeslots_day_slot_number below.
CREATE TABLE IF NOT EXISTS timeslots (
    end_time time(6) not null,
    slot_number integer,
    start_time time(6) not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    version bigint not null,
    day varchar(255) not null check (day in ('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY')),
    type varchar(255) not null check (type in ('CLASS','BREAK','BLOCKED')),
    primary key (id),
    unique (day, start_time, end_time)
);

CREATE TABLE IF NOT EXISTS university_configs (
    active boolean not null,
    days_per_week integer not null check ((days_per_week<=6) and (days_per_week>=5)),
    max_classes_per_day integer not null check (max_classes_per_day>=1),
    timeslots_per_day integer not null check (timeslots_per_day>=1),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    version bigint not null,
    primary key (id)
);

-- =============================================================================
-- 2. Foreign keys (name-guarded for legacy databases)
-- =============================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_batch_working_days_batch') THEN
        ALTER TABLE batch_working_days ADD CONSTRAINT fk_batch_working_days_batch
            FOREIGN KEY (batch_id) REFERENCES batches (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_batches_department') THEN
        ALTER TABLE batches ADD CONSTRAINT fk_batches_department
            FOREIGN KEY (department_id) REFERENCES departments (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_class_sections_batch') THEN
        ALTER TABLE class_sections ADD CONSTRAINT fk_class_sections_batch
            FOREIGN KEY (batch_id) REFERENCES batches (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_class_sessions_batch') THEN
        ALTER TABLE class_sessions ADD CONSTRAINT fk_class_sessions_batch
            FOREIGN KEY (batch_id) REFERENCES batches (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_class_sessions_room') THEN
        ALTER TABLE class_sessions ADD CONSTRAINT fk_class_sessions_room
            FOREIGN KEY (room_id) REFERENCES rooms (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_class_sessions_schedule') THEN
        ALTER TABLE class_sessions ADD CONSTRAINT fk_class_sessions_schedule
            FOREIGN KEY (schedule_id) REFERENCES schedules (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_class_sessions_section') THEN
        ALTER TABLE class_sessions ADD CONSTRAINT fk_class_sessions_section
            FOREIGN KEY (section_id) REFERENCES class_sections (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_class_sessions_subject') THEN
        ALTER TABLE class_sessions ADD CONSTRAINT fk_class_sessions_subject
            FOREIGN KEY (subject_id) REFERENCES subjects (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_class_sessions_teacher') THEN
        ALTER TABLE class_sessions ADD CONSTRAINT fk_class_sessions_teacher
            FOREIGN KEY (teacher_id) REFERENCES teachers (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_class_sessions_timeslot') THEN
        ALTER TABLE class_sessions ADD CONSTRAINT fk_class_sessions_timeslot
            FOREIGN KEY (timeslot_id) REFERENCES timeslots (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_config_break_indices_config') THEN
        ALTER TABLE config_break_indices ADD CONSTRAINT fk_config_break_indices_config
            FOREIGN KEY (config_id) REFERENCES university_configs (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_config_working_days_config') THEN
        ALTER TABLE config_working_days ADD CONSTRAINT fk_config_working_days_config
            FOREIGN KEY (config_id) REFERENCES university_configs (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_department_buildings_building') THEN
        ALTER TABLE department_buildings ADD CONSTRAINT fk_department_buildings_building
            FOREIGN KEY (building_id) REFERENCES buildings (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_department_buildings_department') THEN
        ALTER TABLE department_buildings ADD CONSTRAINT fk_department_buildings_department
            FOREIGN KEY (department_id) REFERENCES departments (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_event_affected_rooms_room') THEN
        ALTER TABLE event_affected_rooms ADD CONSTRAINT fk_event_affected_rooms_room
            FOREIGN KEY (room_id) REFERENCES rooms (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_event_affected_rooms_event') THEN
        ALTER TABLE event_affected_rooms ADD CONSTRAINT fk_event_affected_rooms_event
            FOREIGN KEY (event_id) REFERENCES events (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_event_affected_teachers_teacher') THEN
        ALTER TABLE event_affected_teachers ADD CONSTRAINT fk_event_affected_teachers_teacher
            FOREIGN KEY (teacher_id) REFERENCES teachers (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_event_affected_teachers_event') THEN
        ALTER TABLE event_affected_teachers ADD CONSTRAINT fk_event_affected_teachers_event
            FOREIGN KEY (event_id) REFERENCES events (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_event_affected_timeslots_timeslot') THEN
        ALTER TABLE event_affected_timeslots ADD CONSTRAINT fk_event_affected_timeslots_timeslot
            FOREIGN KEY (timeslot_id) REFERENCES timeslots (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_event_affected_timeslots_event') THEN
        ALTER TABLE event_affected_timeslots ADD CONSTRAINT fk_event_affected_timeslots_event
            FOREIGN KEY (event_id) REFERENCES events (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_pre_allocations_batch') THEN
        ALTER TABLE pre_allocations ADD CONSTRAINT fk_pre_allocations_batch
            FOREIGN KEY (batch_id) REFERENCES batches (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_pre_allocations_room') THEN
        ALTER TABLE pre_allocations ADD CONSTRAINT fk_pre_allocations_room
            FOREIGN KEY (room_id) REFERENCES rooms (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_pre_allocations_schedule') THEN
        ALTER TABLE pre_allocations ADD CONSTRAINT fk_pre_allocations_schedule
            FOREIGN KEY (schedule_id) REFERENCES schedules (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_pre_allocations_subject') THEN
        ALTER TABLE pre_allocations ADD CONSTRAINT fk_pre_allocations_subject
            FOREIGN KEY (subject_id) REFERENCES subjects (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_pre_allocations_teacher') THEN
        ALTER TABLE pre_allocations ADD CONSTRAINT fk_pre_allocations_teacher
            FOREIGN KEY (teacher_id) REFERENCES teachers (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_pre_allocations_timeslot') THEN
        ALTER TABLE pre_allocations ADD CONSTRAINT fk_pre_allocations_timeslot
            FOREIGN KEY (timeslot_id) REFERENCES timeslots (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_room_availability_timeslot') THEN
        ALTER TABLE room_availability ADD CONSTRAINT fk_room_availability_timeslot
            FOREIGN KEY (timeslot_id) REFERENCES timeslots (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_room_availability_room') THEN
        ALTER TABLE room_availability ADD CONSTRAINT fk_room_availability_room
            FOREIGN KEY (room_id) REFERENCES rooms (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_rooms_building') THEN
        ALTER TABLE rooms ADD CONSTRAINT fk_rooms_building
            FOREIGN KEY (building_id) REFERENCES buildings (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_schedules_parent_schedule') THEN
        ALTER TABLE schedules ADD CONSTRAINT fk_schedules_parent_schedule
            FOREIGN KEY (parent_schedule_id) REFERENCES schedules (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_subjects_department') THEN
        ALTER TABLE subjects ADD CONSTRAINT fk_subjects_department
            FOREIGN KEY (department_id) REFERENCES departments (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_teacher_availability_timeslot') THEN
        ALTER TABLE teacher_availability ADD CONSTRAINT fk_teacher_availability_timeslot
            FOREIGN KEY (timeslot_id) REFERENCES timeslots (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_teacher_availability_teacher') THEN
        ALTER TABLE teacher_availability ADD CONSTRAINT fk_teacher_availability_teacher
            FOREIGN KEY (teacher_id) REFERENCES teachers (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_teacher_preferred_buildings_building') THEN
        ALTER TABLE teacher_preferred_buildings ADD CONSTRAINT fk_teacher_preferred_buildings_building
            FOREIGN KEY (building_id) REFERENCES buildings (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_teacher_preferred_buildings_teacher') THEN
        ALTER TABLE teacher_preferred_buildings ADD CONSTRAINT fk_teacher_preferred_buildings_teacher
            FOREIGN KEY (teacher_id) REFERENCES teachers (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_teacher_subjects_subject') THEN
        ALTER TABLE teacher_subjects ADD CONSTRAINT fk_teacher_subjects_subject
            FOREIGN KEY (subject_id) REFERENCES subjects (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_teacher_subjects_teacher') THEN
        ALTER TABLE teacher_subjects ADD CONSTRAINT fk_teacher_subjects_teacher
            FOREIGN KEY (teacher_id) REFERENCES teachers (id);
    END IF;
END $$;

-- =============================================================================
-- 3. Unique indexes (named, matching the guarantees introduced by V1)
-- =============================================================================

CREATE UNIQUE INDEX IF NOT EXISTS uk_buildings_name ON buildings (name);
CREATE UNIQUE INDEX IF NOT EXISTS uk_class_sections_batch_label ON class_sections (batch_id, label);
CREATE UNIQUE INDEX IF NOT EXISTS uk_pre_allocations_schedule_batch_subject_timeslot
    ON pre_allocations (schedule_id, batch_id, subject_id, timeslot_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_timeslots_day_slot_number
    ON timeslots (day, slot_number) WHERE slot_number IS NOT NULL;

-- =============================================================================
-- 4. Foreign-key indexes for hot query paths
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_class_sessions_schedule_id ON class_sessions (schedule_id);
CREATE INDEX IF NOT EXISTS idx_class_sessions_teacher_id  ON class_sessions (teacher_id);
CREATE INDEX IF NOT EXISTS idx_class_sessions_room_id     ON class_sessions (room_id);
CREATE INDEX IF NOT EXISTS idx_class_sessions_section_id  ON class_sessions (section_id);
CREATE INDEX IF NOT EXISTS idx_timeslots_type             ON timeslots (type);
CREATE INDEX IF NOT EXISTS idx_pre_allocations_schedule_id ON pre_allocations (schedule_id);

-- =============================================================================
-- 5. slot_number backfill for legacy timeslot rows
--    (deterministic: order by start_time within each day, appended after the
--    current max slot_number for that day so no collisions can occur)
-- =============================================================================

UPDATE timeslots t
SET slot_number = sub.rn
FROM (
    SELECT t.id,
           (SELECT COALESCE(MAX(d.slot_number), 0)
              FROM timeslots d
             WHERE d.day = t.day AND d.slot_number IS NOT NULL)
           + ROW_NUMBER() OVER (PARTITION BY t.day ORDER BY t.start_time, t.id) AS rn
      FROM timeslots t
     WHERE t.slot_number IS NULL
) sub
WHERE t.id = sub.id;
