-- V5: Durable solve jobs (async schedule generation / partial resolve).
-- -----------------------------------------------------------------------------
-- Solve requests are decoupled from the HTTP request that created them. The
-- API returns a job id immediately; the worker persists status transitions
-- (QUEUED -> RUNNING -> SUCCEEDED / FAILED / CANCELLED) in short transactions
-- so no database transaction is held open while Timefold searches.
--
-- The request snapshot columns (department id, id lists, solving time) let a
-- job be rebuilt without losing the original intent, and problem_id tracks the
-- underlying Timefold problem so cancellation can reach the live solver.

CREATE TABLE IF NOT EXISTS solve_jobs (
    id bigint generated by default as identity,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    version bigint not null,
    elapsed_millis bigint,
    schedule_id bigint not null,
    solving_time_seconds integer,
    department_id bigint,
    problem_id uuid,
    job_type varchar(32) not null,
    status varchar(32) not null,
    score varchar(255),
    best_score varchar(255),
    batch_ids_csv TEXT,
    teacher_ids_csv TEXT,
    room_ids_csv TEXT,
    impacted_session_ids_csv TEXT,
    error_message TEXT,
    started_at timestamp(6),
    finished_at timestamp(6),
    primary key (id)
);

CREATE INDEX IF NOT EXISTS idx_solve_jobs_status   ON solve_jobs (status);
CREATE INDEX IF NOT EXISTS idx_solve_jobs_schedule ON solve_jobs (schedule_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_solve_jobs_schedule') THEN
        ALTER TABLE solve_jobs ADD CONSTRAINT fk_solve_jobs_schedule
            FOREIGN KEY (schedule_id) REFERENCES schedules (id) ON DELETE CASCADE;
    END IF;
END $$;
